name: Deployment project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint code 
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Run deploy
        run: npm run build
